name: "汉化请求"
description: "对一些未汉化模组的汉化请求"
labels: ["B: 汉化请求"]
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "检查项"
    description: "在提交issue之前，请检查以下两项内容："
    options:
    - label: "**我明确作者提供了汉补包/覆盖包的下载，同时汉补包/覆盖包中并没有汉化某模组** 汉补包/覆盖包下载请跳转[官网](https://www.huaijiujing.cn)"
      required: true
    - label: "我已在 [Issues 页面](https://github.com/GRAINALCOHOL/Origincraft-feedback/issues/new/choose) 中搜索，确认了这一汉化未被提交过。"
      required: true
- type: textarea
  id: "yml-2"
  attributes:
    label: 描述
    description: "描述一下目前模组的汉化程度和你期待的汉化程度"
    placeholder: "可以填写文本/粘贴图片/提交链接等..."
  validations:
    required: true
