name: "优化建议"
description: "对整合包的内容/性能优化建议"
labels: ["B: 优化建议"]
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "检查项"
    description: "在提交issue之前，请检查以下两项内容："
    options:
    - label: "**增添的模组能在1.19.2Fabric上加载** 想要搜索某模组的应用版本&加载器，请前往 [MC百科](https://www.mcmod.cn/)"
      required: true
    - label: "我已在 [Issues 页面](https://github.com/GRAINALCOHOL/Origincraft-feedback/issues/new/choose) 中搜索，确认了这一建议未被提交过。"
      required: true
- type: textarea
  id: "yml-2"
  attributes:
    label: 内容
    description: "详细描述具体需要优化哪些地方，修改什么，以及为什么需要？"
    placeholder: "例如:因为游戏帧率波动比较大，我要推荐一个模组，他能优化整合包的稳定性"
  validations:
    required: true
